name: CMake

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        path: valve_source_plugin_navmesh
    - name: Checkout and Build project
      uses: ./valve_source_plugin_navmesh/.github/actions/build
      with:
        repo-path: valve_source_plugin_navmesh

    # --- ARTIFACT UPLOAD STEPS (UPDATED PATHS) ---
    - name: Upload Linux Build Artifact
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: navmesh-plugin-linux
        # Corrected path and filename for Linux
        path: ${{github.workspace}}/build/test/Release/libplugin_navmesh.so

    - name: Upload Windows Build Artifact
          if: runner.os == 'Windows'
          uses: actions/upload-artifact@v4
          with:
            name: navmesh-plugin-windows
            # CORRECTED PATH FOR WINDOWS:
            path: ${{github.workspace}}/build/test/Release/plugin_navmesh.dll

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C Release
