name: CMake
on:
  push:
    branches: [ master ]
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        path: valve_source_plugin_navmesh
    - name: Checkout and Build project
      uses: ./valve_source_plugin_navmesh/.github/actions/build
      with:
        repo-path: valve_source_plugin_navmesh

    # --- ADD THESE DEBUGGING STEPS ---
    - name: List Build Directory (Linux)
      if: runner.os == 'Linux'
      working-directory: ${{github.workspace}}/build
      run: |
        echo "Listing contents of build directory (Linux):"
        ls -R .

    - name: List Build Directory (Windows)
      if: runner.os == 'Windows'
      working-directory: ${{github.workspace}}/build
      run: |
        echo "Listing contents of build directory (Windows):"
        dir /s .
    # --- END DEBUGGING STEPS ---

    - name: Upload Linux Build Artifact
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: navmesh-plugin-linux
        path: ${{github.workspace}}/build/Release/valve_source_plugin_navmesh.so # This path is currently incorrect
        # ... (rest of your existing upload step)

    - name: Upload Windows Build Artifact
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: navmesh-plugin-windows
        path: ${{github.workspace}}/build/Release/valve_source_plugin_navmesh.dll # This path is currently incorrect
        # ... (rest of your existing upload step)

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C Release
