name: CMake

on:
  push:
    branches: [ master ]
  workflow_dispatch: # Allows manual triggering from GitHub UI
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        path: valve_source_plugin_navmesh

    - name: Checkout and Build project # This step now handles BOTH building and uploading via action.yml
      uses: ./valve_source_plugin_navmesh/.github/actions/build
      with:
        repo-path: valve_source_plugin_navmesh

    # NO UPLOAD-ARTIFACT STEPS HERE - they are handled by .github/actions/build/action.yml

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C Release
