name: CMake

on:
  # push: # Commented out this section to prevent automatic runs on push
  #   branches: [ master ]
  workflow_dispatch: # Keep this to allow manual triggering from GitHub UI
  pull_request: # You might want to keep this for pull requests, or comment it out too if preferred
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        path: valve_source_plugin_navmesh

    # Removed: Install 32-bit build dependencies (Linux) as we are now targeting 64-bit

    - name: Checkout and Build project
      uses: ./valve_source_plugin_navmesh/.github/actions/build
      with:
        repo-path: valve_source_plugin_navmesh

    - name: Test
      # --- FIX: Corrected working directory for Windows build output ---
      working-directory: ${{github.workspace}}/valve_source_plugin_navmesh/build_windows
      run: ctest -C Release
